package org.caotc.unit4j.core.common.util.model;

import com.google.common.collect.ImmutableSet;
import com.google.common.reflect.TypeToken;
import lombok.experimental.UtilityClass;
import org.caotc.unit4j.core.common.reflect.property.accessor.PropertyAccessor;
import org.caotc.unit4j.core.common.reflect.property.accessor.PropertyReader;

import java.lang.reflect.Constructor;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.util.Arrays;
import java.util.stream.Stream;

/**
 * @author caotc
 * @date 2022-09-08
 * @since 1.0.0
 */
@UtilityClass
public class Constant {
    public static final Field STRING_FIELD_OBJECT_STRING_FIELD;
    public static final Field FINAL_FIELD_OBJECT_STRING_FIELD;
    public static final Field STATIC_FIELD_OBJECT_STRING_FIELD;
    public static final Field CHILDREN_LONG_FIELD_OBJECT_LONG_FIELD;
    public static final Field CHILDREN_SAME_NAME_FIELD_OBJECT_STRING_FIELD;
    public static final Field MULTIPLE_FIELD_OBJECT_STRING_FIELD;
    public static final Field MULTIPLE_FIELD_OBJECT_INTEGER_FIELD;
    public static final Field MULTIPLE_FIELD_OBJECT_INT_FIELD;
    public static final Field MULTIPLE_FIELD_OBJECT_BOOLEAN_FIELD;
    public static final Field STRING_FIELD_AND_STRING_FIELD_GET_METHOD_OBJECT_STRING_FIELD;
    public static final Field STRING_FIELD_AND_STRING_FIELD_SET_METHOD_OBJECT_STRING_FIELD;
    public static final Method STRING_FIELD_GET_METHOD_OBJECT_GET_STRING_FIELD_METHOD;
    public static final Method STRING_FIELD_FLUENT_GET_METHOD_OBJECT_STRING_FIELD_METHOD;
    public static final Method STRING_FIELD_AND_STRING_FIELD_GET_METHOD_OBJECT_GET_STRING_FIELD_METHOD;
    public static final Method STRING_FIELD_GETTER_GET_STRING_FIELD_METHOD;
    public static final Method STRING_FIELD_GETTER_OBJECT_GET_STRING_FIELD_METHOD;
    public static final Method BOOLEAN_FIELD_IS_METHOD_OBJECT_IS_BOOLEAN_FIELD_METHOD;
    public static final Method BOOLEAN_FIELD_GET_METHOD_OBJECT_GET_BOOLEAN_FIELD_METHOD;
    public static final Method STRING_FIELD_SET_METHOD_OBJECT_SET_STRING_FIELD_METHOD;
    public static final Method STRING_FIELD_FLUENT_SET_METHOD_OBJECT_STRING_FIELD_METHOD;
    public static final Method STRING_FIELD_AND_STRING_FIELD_SET_METHOD_OBJECT_SET_STRING_FIELD_METHOD;
    public static final Method STRING_FIELD_SETTER_SET_STRING_FIELD_METHOD;
    public static final Method STRING_FIELD_SETTER_OBJECT_SET_STRING_FIELD_METHOD;
    public static final Method STRING_FIELD_CHAIN_SET_METHOD_OBJECT_SET_STRING_FIELD_METHOD;
    public static final Method DUPLICATE_NUMBER_FIELD_SET_METHOD_OBJECT_NUMBER_SET_NUMBER_FIELD_METHOD;
    public static final Method DUPLICATE_NUMBER_FIELD_SET_METHOD_OBJECT_INT_SET_NUMBER_FIELD_METHOD;
    public static final ImmutableSet<Method> STRING_FIELD_GETTER_OBJECT_GET_METHODS;
    public static final ImmutableSet<Method> STRING_FIELD_SETTER_OBJECT_SET_METHODS;
    public static final ImmutableSet<Method> DUPLICATE_NUMBER_FIELD_SET_METHOD_OBJECT_SET_METHODS;
    public static final ImmutableSet<Method> OBJECT_METHODS;
    public static final ImmutableSet<Method> STRING_FIELD_GET_METHOD_OBJECT_METHODS;
    public static final ImmutableSet<Method> STRING_FIELD_FLUENT_GET_METHOD_OBJECT_METHODS;
    public static final ImmutableSet<Method> STRING_FIELD_AND_STRING_FIELD_GET_METHOD_OBJECT_METHODS;
    public static final ImmutableSet<Method> STRING_FIELD_GETTER_OBJECT_METHODS;
    public static final ImmutableSet<Method> BOOLEAN_FIELD_IS_METHOD_OBJECT_METHODS;
    public static final ImmutableSet<Method> BOOLEAN_FIELD_GET_METHOD_OBJECT_METHODS;
    public static final ImmutableSet<Method> STRING_FIELD_SET_METHOD_OBJECT_METHODS;
    public static final ImmutableSet<Method> STRING_FIELD_FLUENT_SET_METHOD_OBJECT_METHODS;
    public static final ImmutableSet<Method> STRING_FIELD_AND_STRING_FIELD_SET_METHOD_OBJECT_METHODS;
    public static final ImmutableSet<Method> STRING_FIELD_CHAIN_SET_METHOD_OBJECT_METHODS;
    public static final ImmutableSet<Method> STRING_FIELD_SETTER_OBJECT_METHODS;
    public static final ImmutableSet<Method> DUPLICATE_NUMBER_FIELD_SET_METHOD_OBJECT_METHODS;
    public static final Constructor<NoFieldObject> NO_FIELD_OBJECT_CONSTRUCTOR;
    public static final Constructor<FinalFieldObject> FINAL_FIELD_OBJECT_CONSTRUCTOR;
    public static final Constructor<MultipleFieldObject> MULTIPLE_FIELD_OBJECT_CONSTRUCTOR;
    public static final Constructor<StaticFieldObject> STATIC_FIELD_OBJECT_CONSTRUCTOR;
    public static final Constructor<StringFieldObject> STRING_FIELD_OBJECT_CONSTRUCTOR;
    public static final Constructor<ChildrenLongFieldObject> CHILDREN_LONG_FIELD_OBJECT_CONSTRUCTOR;
    public static final Constructor<ChildrenSameNameFieldObject> CHILDREN_SAME_NAME_FIELD_OBJECT_CONSTRUCTOR;
    public static final Constructor<PrivateConstructObject> PRIVATE_CONSTRUCT_OBJECT_CONSTRUCTOR;
    public static final Constructor<ProtectedConstructObject> PROTECTED_CONSTRUCT_OBJECT_CONSTRUCTOR;
    public static final Constructor<ProtectedConstructChildrenObject> PROTECTED_CONSTRUCT_CHILDREN_OBJECT_CONSTRUCTOR;
    public static final ImmutableSet<Constructor<MultipleConstructObject>> MULTIPLE_CONSTRUCT_OBJECT_CONSTRUCTORS;
    public static final Constructor<StringFieldGetMethodObject> STRING_FIELD_GET_METHOD_OBJECT_CONSTRUCTOR;
    public static final Constructor<StringFieldFluentGetMethodObject> STRING_FIELD_FLUENT_GET_METHOD_OBJECT_CONSTRUCTOR;
    public static final Constructor<StringFieldAndStringFieldGetMethodObject> STRING_FIELD_AND_STRING_FIELD_GET_METHOD_OBJECT_CONSTRUCTOR;
    public static final Constructor<StringFieldGetterObject> STRING_FIELD_GETTER_OBJECT_CONSTRUCTOR;
    public static final Constructor<BooleanFieldIsMethodObject> BOOLEAN_FIELD_IS_METHOD_OBJECT_CONSTRUCTOR;
    public static final Constructor<BooleanFieldGetMethodObject> BOOLEAN_FIELD_GET_METHOD_OBJECT_CONSTRUCTOR;
    public static final Constructor<StringFieldSetMethodObject> STRING_FIELD_SET_METHOD_OBJECT_CONSTRUCTOR;
    public static final Constructor<StringFieldFluentSetMethodObject> STRING_FIELD_FLUENT_SET_METHOD_OBJECT_CONSTRUCTOR;
    public static final Constructor<StringFieldAndStringFieldSetMethodObject> STRING_FIELD_AND_STRING_FIELD_SET_METHOD_OBJECT_CONSTRUCTOR;
    public static final Constructor<StringFieldChainSetMethodObject> STRING_FIELD_CHAIN_SET_METHOD_OBJECT_CONSTRUCTOR;
    public static final Constructor<StringFieldSetterObject> STRING_FIELD_SETTER_OBJECT_CONSTRUCTOR;
    public static final Constructor<DuplicateNumberFieldSetMethodObject> DUPLICATE_NUMBER_FIELD_SET_METHOD_OBJECT_CONSTRUCTOR;
    public static final ImmutableSet<Field> STRING_FIELD_OBJECT_FIELDS;
    public static final ImmutableSet<Field> CHILDREN_LONG_FIELD_OBJECT_FIELDS;
    public static final ImmutableSet<Field> CHILDREN_SAME_NAME_FIELD_OBJECT_FIELDS;
    public static final ImmutableSet<Field> FINAL_FIELD_OBJECT_FIELDS;
    public static final ImmutableSet<Field> STATIC_FIELD_OBJECT_FIELDS;
    public static final ImmutableSet<Field> MULTIPLE_FIELD_OBJECT_FIELDS;
    public static final PropertyReader<BooleanFieldGetMethodObject, Boolean> BOOLEAN_FIELD_GET_METHOD_OBJECT_BOOLEAN_FIELD_PROPERTY_READER;
    public static final PropertyReader<BooleanFieldIsMethodObject, Boolean> BOOLEAN_FIELD_IS_METHOD_OBJECT_BOOLEAN_FIELD_PROPERTY_READER;
    public static final ImmutableSet<PropertyReader<ChildrenLongFieldObject, ?>> CHILDREN_LONG_FIELD_OBJECT_PROPERTY_READERS;
    public static final ImmutableSet<PropertyReader<ChildrenSameNameFieldObject, ?>> CHILDREN_SAME_NAME_FIELD_OBJECT_PROPERTY_READERS;
    public static final PropertyReader<FinalFieldObject, String> FINAL_FIELD_OBJECT_STRING_FIELD_PROPERTY_READER;
    public static final ImmutableSet<PropertyReader<MultipleFieldObject, ?>> MULTIPLE_FIELD_OBJECT_PROPERTY_READERS;
    public static final ImmutableSet<PropertyReader<StringFieldAndStringFieldGetMethodObject, ?>> STRING_FIELD_AND_STRING_FIELD_GET_METHOD_OBJECT_PROPERTY_READERS;
    public static final PropertyReader<StringFieldAndStringFieldSetMethodObject, String> STRING_FIELD_AND_STRING_FIELD_SET_METHOD_OBJECT_STRING_FIELD_PROPERTY_READER;
    public static final PropertyReader<StringFieldFluentGetMethodObject, String> STRING_FIELD_FLUENT_GET_METHOD_OBJECT_STRING_FIELD_PROPERTY_READER;
    public static final PropertyReader<StringFieldGetMethodObject, String> STRING_FIELD_GET_METHOD_OBJECT_STRING_FIELD_PROPERTY_READER;
    public static final PropertyReader<StringFieldGetter, String> STRING_FIELD_GETTER_STRING_FIELD_PROPERTY_READER;
    public static final ImmutableSet<PropertyReader<StringFieldGetterObject, ?>> STRING_FIELD_GETTER_OBJECT_PROPERTY_READERS;
    public static final PropertyReader<StringFieldObject, String> STRING_FIELD_OBJECT_STRING_FIELD_PROPERTY_READER;

    static {
        try {
            STRING_FIELD_OBJECT_STRING_FIELD = StringFieldObject.class.getDeclaredField(StringFieldObject.Fields.STRING_FIELD);
            FINAL_FIELD_OBJECT_STRING_FIELD = FinalFieldObject.class.getDeclaredField(FinalFieldObject.Fields.STRING_FIELD);
            STATIC_FIELD_OBJECT_STRING_FIELD = StaticFieldObject.class.getDeclaredField("stringField");
            CHILDREN_LONG_FIELD_OBJECT_LONG_FIELD = ChildrenLongFieldObject.class.getDeclaredField(ChildrenLongFieldObject.Fields.LONG_FIELD);
            CHILDREN_SAME_NAME_FIELD_OBJECT_STRING_FIELD = ChildrenSameNameFieldObject.class.getDeclaredField(ChildrenSameNameFieldObject.Fields.STRING_FIELD);
            MULTIPLE_FIELD_OBJECT_STRING_FIELD = MultipleFieldObject.class.getDeclaredField(MultipleFieldObject.Fields.STRING_FIELD);
            MULTIPLE_FIELD_OBJECT_INTEGER_FIELD = MultipleFieldObject.class.getDeclaredField(MultipleFieldObject.Fields.INTEGER_FIELD);
            MULTIPLE_FIELD_OBJECT_INT_FIELD = MultipleFieldObject.class.getDeclaredField(MultipleFieldObject.Fields.INT_FIELD);
            MULTIPLE_FIELD_OBJECT_BOOLEAN_FIELD = MultipleFieldObject.class.getDeclaredField(MultipleFieldObject.Fields.BOOLEAN_FIELD);
            STRING_FIELD_AND_STRING_FIELD_GET_METHOD_OBJECT_STRING_FIELD = StringFieldAndStringFieldGetMethodObject.class.getDeclaredField(StringFieldAndStringFieldGetMethodObject.Fields.STRING_FIELD);
            STRING_FIELD_AND_STRING_FIELD_SET_METHOD_OBJECT_STRING_FIELD = StringFieldAndStringFieldSetMethodObject.class.getDeclaredField(StringFieldAndStringFieldSetMethodObject.Fields.STRING_FIELD);
            STRING_FIELD_GET_METHOD_OBJECT_GET_STRING_FIELD_METHOD = StringFieldGetMethodObject.class.getDeclaredMethod("getStringField");
            STRING_FIELD_FLUENT_GET_METHOD_OBJECT_STRING_FIELD_METHOD = StringFieldFluentGetMethodObject.class.getDeclaredMethod("stringField");
            STRING_FIELD_AND_STRING_FIELD_GET_METHOD_OBJECT_GET_STRING_FIELD_METHOD = StringFieldAndStringFieldGetMethodObject.class.getDeclaredMethod("getStringField");
            STRING_FIELD_GETTER_GET_STRING_FIELD_METHOD = StringFieldGetter.class.getDeclaredMethod("getStringField");
            STRING_FIELD_GETTER_OBJECT_GET_STRING_FIELD_METHOD = StringFieldGetterObject.class.getDeclaredMethod("getStringField");
            BOOLEAN_FIELD_IS_METHOD_OBJECT_IS_BOOLEAN_FIELD_METHOD = BooleanFieldIsMethodObject.class.getDeclaredMethod("isBooleanField");
            BOOLEAN_FIELD_GET_METHOD_OBJECT_GET_BOOLEAN_FIELD_METHOD = BooleanFieldGetMethodObject.class.getDeclaredMethod("getBooleanField");
            STRING_FIELD_SET_METHOD_OBJECT_SET_STRING_FIELD_METHOD = StringFieldSetMethodObject.class.getDeclaredMethod("setStringField", String.class);
            STRING_FIELD_FLUENT_SET_METHOD_OBJECT_STRING_FIELD_METHOD = StringFieldFluentSetMethodObject.class.getDeclaredMethod("stringField", String.class);
            STRING_FIELD_AND_STRING_FIELD_SET_METHOD_OBJECT_SET_STRING_FIELD_METHOD = StringFieldAndStringFieldSetMethodObject.class.getDeclaredMethod("setStringField", String.class);
            STRING_FIELD_SETTER_SET_STRING_FIELD_METHOD = StringFieldSetter.class.getDeclaredMethod("setStringField", String.class);
            STRING_FIELD_SETTER_OBJECT_SET_STRING_FIELD_METHOD = StringFieldSetterObject.class.getDeclaredMethod("setStringField", String.class);
            STRING_FIELD_CHAIN_SET_METHOD_OBJECT_SET_STRING_FIELD_METHOD = StringFieldChainSetMethodObject.class.getDeclaredMethod("setStringField", String.class);
            DUPLICATE_NUMBER_FIELD_SET_METHOD_OBJECT_NUMBER_SET_NUMBER_FIELD_METHOD = DuplicateNumberFieldSetMethodObject.class.getDeclaredMethod("setNumberField", Number.class);
            DUPLICATE_NUMBER_FIELD_SET_METHOD_OBJECT_INT_SET_NUMBER_FIELD_METHOD = DuplicateNumberFieldSetMethodObject.class.getDeclaredMethod("setNumberField", int.class);
            STRING_FIELD_GETTER_OBJECT_GET_METHODS = ImmutableSet.of(STRING_FIELD_GETTER_GET_STRING_FIELD_METHOD, STRING_FIELD_GETTER_OBJECT_GET_STRING_FIELD_METHOD);
            STRING_FIELD_SETTER_OBJECT_SET_METHODS = ImmutableSet.of(STRING_FIELD_SETTER_SET_STRING_FIELD_METHOD, STRING_FIELD_SETTER_OBJECT_SET_STRING_FIELD_METHOD);
            DUPLICATE_NUMBER_FIELD_SET_METHOD_OBJECT_SET_METHODS = ImmutableSet.of(DUPLICATE_NUMBER_FIELD_SET_METHOD_OBJECT_NUMBER_SET_NUMBER_FIELD_METHOD, DUPLICATE_NUMBER_FIELD_SET_METHOD_OBJECT_INT_SET_NUMBER_FIELD_METHOD);
            OBJECT_METHODS = Arrays.stream(Object.class.getDeclaredMethods()).collect(ImmutableSet.toImmutableSet());
            STRING_FIELD_GET_METHOD_OBJECT_METHODS = Stream.concat(OBJECT_METHODS.stream(), Stream.of(STRING_FIELD_GET_METHOD_OBJECT_GET_STRING_FIELD_METHOD)).collect(ImmutableSet.toImmutableSet());
            STRING_FIELD_FLUENT_GET_METHOD_OBJECT_METHODS = Stream.concat(OBJECT_METHODS.stream(), Stream.of(STRING_FIELD_FLUENT_GET_METHOD_OBJECT_STRING_FIELD_METHOD)).collect(ImmutableSet.toImmutableSet());
            STRING_FIELD_AND_STRING_FIELD_GET_METHOD_OBJECT_METHODS = Stream.concat(OBJECT_METHODS.stream(), Stream.of(STRING_FIELD_AND_STRING_FIELD_GET_METHOD_OBJECT_GET_STRING_FIELD_METHOD)).collect(ImmutableSet.toImmutableSet());
            STRING_FIELD_GETTER_OBJECT_METHODS = Stream.concat(OBJECT_METHODS.stream(), Stream.of(STRING_FIELD_GETTER_GET_STRING_FIELD_METHOD, STRING_FIELD_GETTER_OBJECT_GET_STRING_FIELD_METHOD)).collect(ImmutableSet.toImmutableSet());
            BOOLEAN_FIELD_IS_METHOD_OBJECT_METHODS = Stream.concat(OBJECT_METHODS.stream(), Stream.of(BOOLEAN_FIELD_IS_METHOD_OBJECT_IS_BOOLEAN_FIELD_METHOD)).collect(ImmutableSet.toImmutableSet());
            BOOLEAN_FIELD_GET_METHOD_OBJECT_METHODS = Stream.concat(OBJECT_METHODS.stream(), Stream.of(BOOLEAN_FIELD_GET_METHOD_OBJECT_GET_BOOLEAN_FIELD_METHOD)).collect(ImmutableSet.toImmutableSet());
            STRING_FIELD_SET_METHOD_OBJECT_METHODS = Stream.concat(OBJECT_METHODS.stream(), Stream.of(STRING_FIELD_SET_METHOD_OBJECT_SET_STRING_FIELD_METHOD)).collect(ImmutableSet.toImmutableSet());
            STRING_FIELD_FLUENT_SET_METHOD_OBJECT_METHODS = Stream.concat(OBJECT_METHODS.stream(), Stream.of(STRING_FIELD_FLUENT_SET_METHOD_OBJECT_STRING_FIELD_METHOD)).collect(ImmutableSet.toImmutableSet());
            STRING_FIELD_AND_STRING_FIELD_SET_METHOD_OBJECT_METHODS = Stream.concat(OBJECT_METHODS.stream(), Stream.of(STRING_FIELD_AND_STRING_FIELD_SET_METHOD_OBJECT_SET_STRING_FIELD_METHOD)).collect(ImmutableSet.toImmutableSet());
            STRING_FIELD_CHAIN_SET_METHOD_OBJECT_METHODS = Stream.concat(OBJECT_METHODS.stream(), Stream.of(STRING_FIELD_CHAIN_SET_METHOD_OBJECT_SET_STRING_FIELD_METHOD)).collect(ImmutableSet.toImmutableSet());
            STRING_FIELD_SETTER_OBJECT_METHODS = Stream.concat(OBJECT_METHODS.stream(), Stream.of(STRING_FIELD_SETTER_SET_STRING_FIELD_METHOD, STRING_FIELD_SETTER_OBJECT_SET_STRING_FIELD_METHOD)).collect(ImmutableSet.toImmutableSet());
            DUPLICATE_NUMBER_FIELD_SET_METHOD_OBJECT_METHODS = Stream.concat(OBJECT_METHODS.stream(), DUPLICATE_NUMBER_FIELD_SET_METHOD_OBJECT_SET_METHODS.stream()).collect(ImmutableSet.toImmutableSet());
            NO_FIELD_OBJECT_CONSTRUCTOR = NoFieldObject.class.getDeclaredConstructor();
            FINAL_FIELD_OBJECT_CONSTRUCTOR = FinalFieldObject.class.getDeclaredConstructor();
            MULTIPLE_FIELD_OBJECT_CONSTRUCTOR = MultipleFieldObject.class.getDeclaredConstructor();
            STATIC_FIELD_OBJECT_CONSTRUCTOR = StaticFieldObject.class.getDeclaredConstructor();
            STRING_FIELD_OBJECT_CONSTRUCTOR = StringFieldObject.class.getDeclaredConstructor();
            CHILDREN_LONG_FIELD_OBJECT_CONSTRUCTOR = ChildrenLongFieldObject.class.getDeclaredConstructor();
            CHILDREN_SAME_NAME_FIELD_OBJECT_CONSTRUCTOR = ChildrenSameNameFieldObject.class.getDeclaredConstructor();
            PRIVATE_CONSTRUCT_OBJECT_CONSTRUCTOR = PrivateConstructObject.class.getDeclaredConstructor(String.class, Integer.class, int.class, boolean.class);
            PROTECTED_CONSTRUCT_OBJECT_CONSTRUCTOR = ProtectedConstructObject.class.getDeclaredConstructor(String.class, Integer.class, int.class, boolean.class);
            PROTECTED_CONSTRUCT_CHILDREN_OBJECT_CONSTRUCTOR = ProtectedConstructChildrenObject.class.getConstructor(String.class, Integer.class, int.class, boolean.class);
            //noinspection unchecked
            MULTIPLE_CONSTRUCT_OBJECT_CONSTRUCTORS = Arrays.stream(MultipleConstructObject.class.getDeclaredConstructors()).map(c -> (Constructor<MultipleConstructObject>) c).collect(ImmutableSet.toImmutableSet());
            STRING_FIELD_GET_METHOD_OBJECT_CONSTRUCTOR = StringFieldGetMethodObject.class.getDeclaredConstructor();
            STRING_FIELD_FLUENT_GET_METHOD_OBJECT_CONSTRUCTOR = StringFieldFluentGetMethodObject.class.getDeclaredConstructor();
            STRING_FIELD_AND_STRING_FIELD_GET_METHOD_OBJECT_CONSTRUCTOR = StringFieldAndStringFieldGetMethodObject.class.getDeclaredConstructor();
            STRING_FIELD_GETTER_OBJECT_CONSTRUCTOR = StringFieldGetterObject.class.getDeclaredConstructor();
            BOOLEAN_FIELD_IS_METHOD_OBJECT_CONSTRUCTOR = BooleanFieldIsMethodObject.class.getDeclaredConstructor();
            BOOLEAN_FIELD_GET_METHOD_OBJECT_CONSTRUCTOR = BooleanFieldGetMethodObject.class.getDeclaredConstructor();
            STRING_FIELD_SET_METHOD_OBJECT_CONSTRUCTOR = StringFieldSetMethodObject.class.getDeclaredConstructor();
            STRING_FIELD_FLUENT_SET_METHOD_OBJECT_CONSTRUCTOR = StringFieldFluentSetMethodObject.class.getDeclaredConstructor();
            STRING_FIELD_AND_STRING_FIELD_SET_METHOD_OBJECT_CONSTRUCTOR = StringFieldAndStringFieldSetMethodObject.class.getDeclaredConstructor();
            STRING_FIELD_CHAIN_SET_METHOD_OBJECT_CONSTRUCTOR = StringFieldChainSetMethodObject.class.getDeclaredConstructor();
            STRING_FIELD_SETTER_OBJECT_CONSTRUCTOR = StringFieldSetterObject.class.getDeclaredConstructor();
            DUPLICATE_NUMBER_FIELD_SET_METHOD_OBJECT_CONSTRUCTOR = DuplicateNumberFieldSetMethodObject.class.getDeclaredConstructor();
            STRING_FIELD_OBJECT_FIELDS = ImmutableSet.of(STRING_FIELD_OBJECT_STRING_FIELD);
            CHILDREN_LONG_FIELD_OBJECT_FIELDS = ImmutableSet.<Field>builder().addAll(STRING_FIELD_OBJECT_FIELDS).add(CHILDREN_LONG_FIELD_OBJECT_LONG_FIELD).build();
            CHILDREN_SAME_NAME_FIELD_OBJECT_FIELDS = ImmutableSet.<Field>builder().addAll(STRING_FIELD_OBJECT_FIELDS).add(CHILDREN_SAME_NAME_FIELD_OBJECT_STRING_FIELD).build();
            FINAL_FIELD_OBJECT_FIELDS = ImmutableSet.of(FINAL_FIELD_OBJECT_STRING_FIELD);
            STATIC_FIELD_OBJECT_FIELDS = ImmutableSet.of(STATIC_FIELD_OBJECT_STRING_FIELD);
            MULTIPLE_FIELD_OBJECT_FIELDS = ImmutableSet.of(MULTIPLE_FIELD_OBJECT_STRING_FIELD, MULTIPLE_FIELD_OBJECT_INTEGER_FIELD, MULTIPLE_FIELD_OBJECT_INT_FIELD, MULTIPLE_FIELD_OBJECT_BOOLEAN_FIELD);
            BOOLEAN_FIELD_GET_METHOD_OBJECT_BOOLEAN_FIELD_PROPERTY_READER = PropertyReader.from(BOOLEAN_FIELD_GET_METHOD_OBJECT_GET_BOOLEAN_FIELD_METHOD, "booleanField");
            BOOLEAN_FIELD_IS_METHOD_OBJECT_BOOLEAN_FIELD_PROPERTY_READER = PropertyReader.from(BOOLEAN_FIELD_IS_METHOD_OBJECT_IS_BOOLEAN_FIELD_METHOD, "booleanField");
            CHILDREN_LONG_FIELD_OBJECT_PROPERTY_READERS = CHILDREN_LONG_FIELD_OBJECT_FIELDS.stream().map(PropertyAccessor::<ChildrenLongFieldObject, Object>from).collect(ImmutableSet.toImmutableSet());
            CHILDREN_SAME_NAME_FIELD_OBJECT_PROPERTY_READERS = CHILDREN_SAME_NAME_FIELD_OBJECT_FIELDS.stream().map(PropertyAccessor::<ChildrenSameNameFieldObject, String>from).collect(ImmutableSet.toImmutableSet());
            FINAL_FIELD_OBJECT_STRING_FIELD_PROPERTY_READER = PropertyAccessor.from(FINAL_FIELD_OBJECT_STRING_FIELD);
            MULTIPLE_FIELD_OBJECT_PROPERTY_READERS = MULTIPLE_FIELD_OBJECT_FIELDS.stream().map(PropertyAccessor::<MultipleFieldObject, Object>from).collect(ImmutableSet.toImmutableSet());
            STRING_FIELD_AND_STRING_FIELD_GET_METHOD_OBJECT_PROPERTY_READERS = ImmutableSet.of(PropertyAccessor.from(STRING_FIELD_AND_STRING_FIELD_GET_METHOD_OBJECT_STRING_FIELD), PropertyReader.from(STRING_FIELD_AND_STRING_FIELD_GET_METHOD_OBJECT_GET_STRING_FIELD_METHOD, StringFieldAndStringFieldGetMethodObject.Fields.STRING_FIELD));
            STRING_FIELD_AND_STRING_FIELD_SET_METHOD_OBJECT_STRING_FIELD_PROPERTY_READER = PropertyAccessor.from(STRING_FIELD_AND_STRING_FIELD_SET_METHOD_OBJECT_STRING_FIELD);
            STRING_FIELD_FLUENT_GET_METHOD_OBJECT_STRING_FIELD_PROPERTY_READER = PropertyReader.from(STRING_FIELD_FLUENT_GET_METHOD_OBJECT_STRING_FIELD_METHOD, "stringField");
            STRING_FIELD_GET_METHOD_OBJECT_STRING_FIELD_PROPERTY_READER = PropertyReader.from(STRING_FIELD_GET_METHOD_OBJECT_GET_STRING_FIELD_METHOD, "stringField");
            STRING_FIELD_GETTER_STRING_FIELD_PROPERTY_READER = PropertyReader.from(STRING_FIELD_GETTER_GET_STRING_FIELD_METHOD, "stringField");
            STRING_FIELD_GETTER_OBJECT_PROPERTY_READERS = STRING_FIELD_GETTER_OBJECT_GET_METHODS.stream().map(method -> PropertyReader.from(TypeToken.of(StringFieldGetterObject.class).method(method), "stringField")).collect(ImmutableSet.toImmutableSet());
            STRING_FIELD_OBJECT_STRING_FIELD_PROPERTY_READER = PropertyAccessor.from(STRING_FIELD_OBJECT_STRING_FIELD);
        } catch (NoSuchFieldException | NoSuchMethodException e) {
            throw new RuntimeException(e);
        }
    }
}
