package org.caotc.unit4j.core.common.util.provider;

import com.google.common.collect.ImmutableSet;
import com.google.common.reflect.TypeToken;
import lombok.experimental.UtilityClass;
import org.caotc.unit4j.core.common.reflect.property.AccessibleProperty;
import org.caotc.unit4j.core.common.reflect.property.ReadableProperty;
import org.caotc.unit4j.core.common.reflect.property.WritableProperty;
import org.caotc.unit4j.core.common.reflect.property.accessor.PropertyAccessor;
import org.caotc.unit4j.core.common.reflect.property.accessor.PropertyReader;
import org.caotc.unit4j.core.common.reflect.property.accessor.PropertyWriter;
import org.caotc.unit4j.core.common.util.ReflectionUtil;
import org.caotc.unit4j.core.common.util.model.*;

import java.lang.reflect.Constructor;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.util.Arrays;
import java.util.stream.Stream;

/**
 * @author caotc
 * @date 2022-09-08
 * @since 1.0.0
 */
@UtilityClass
public class Constant {
    public static final Field STRING_FIELD_OBJECT_STRING_FIELD;
    public static final Field FINAL_FIELD_OBJECT_STRING_FIELD;
    public static final Field GENERIC_FIELD_OBJECT_GENERIC_FIELD;
    public static final Field STATIC_FIELD_OBJECT_STRING_FIELD;
    public static final Field CHILDREN_LONG_FIELD_OBJECT_LONG_FIELD;
    public static final Field CHILDREN_SAME_NAME_FIELD_OBJECT_STRING_FIELD;
    public static final Field COMPOSITE_FIELD_OBJECT_INTERNAL_FIELD;
    public static final Field MULTIPLE_FIELD_OBJECT_STRING_FIELD;
    public static final Field MULTIPLE_FIELD_OBJECT_INTEGER_FIELD;
    public static final Field MULTIPLE_FIELD_OBJECT_INT_FIELD;
    public static final Field MULTIPLE_FIELD_OBJECT_BOOLEAN_FIELD;
    public static final Field STRING_FIELD_AND_STRING_FIELD_GET_METHOD_OBJECT_STRING_FIELD;
    public static final Field STRING_FIELD_AND_STRING_FIELD_SET_METHOD_OBJECT_STRING_FIELD;
    public static final Method GENERIC_FIELD_GETTER_GET_GENERIC_FIELD_METHOD;
    public static final Method GENERIC_FIELD_SETTER_SET_GENERIC_FIELD_METHOD;
    public static final Method INTEGER_GENERIC_FIELD_GETTER_GET_GENERIC_FIELD_METHOD;
    public static final Method INTEGER_GENERIC_FIELD_GETTER_BRIDGE_GET_GENERIC_FIELD_METHOD;
    public static final Method LONG_GENERIC_FIELD_SETTER_SET_GENERIC_FIELD_METHOD;
    public static final Method LONG_GENERIC_FIELD_SETTER_BRIDGE_SET_GENERIC_FIELD_METHOD;
    public static final Method STRING_FIELD_GET_METHOD_OBJECT_GET_STRING_FIELD_METHOD;
    public static final Method STRING_FIELD_FLUENT_GET_METHOD_OBJECT_STRING_FIELD_METHOD;
    public static final Method STRING_FIELD_AND_STRING_FIELD_GET_METHOD_OBJECT_GET_STRING_FIELD_METHOD;
    public static final Method STRING_FIELD_GETTER_GET_STRING_FIELD_METHOD;
    public static final Method STRING_FIELD_GETTER_OBJECT_GET_STRING_FIELD_METHOD;
    public static final Method BOOLEAN_FIELD_IS_METHOD_OBJECT_IS_BOOLEAN_FIELD_METHOD;
    public static final Method BOOLEAN_FIELD_GET_METHOD_OBJECT_GET_BOOLEAN_FIELD_METHOD;
    public static final Method STRING_FIELD_SET_METHOD_OBJECT_SET_STRING_FIELD_METHOD;
    public static final Method STRING_FIELD_FLUENT_SET_METHOD_OBJECT_STRING_FIELD_METHOD;
    public static final Method STRING_FIELD_AND_STRING_FIELD_SET_METHOD_OBJECT_SET_STRING_FIELD_METHOD;
    public static final Method STRING_FIELD_SETTER_SET_STRING_FIELD_METHOD;
    public static final Method STRING_FIELD_SETTER_OBJECT_SET_STRING_FIELD_METHOD;
    public static final Method STRING_FIELD_CHAIN_SET_METHOD_OBJECT_SET_STRING_FIELD_METHOD;
    public static final Method DUPLICATE_NUMBER_FIELD_SET_METHOD_OBJECT_NUMBER_SET_NUMBER_FIELD_METHOD;
    public static final Method DUPLICATE_NUMBER_FIELD_SET_METHOD_OBJECT_INT_SET_NUMBER_FIELD_METHOD;
    public static final Method COMPOSITE_GETTER_OBJECT_GET_INTERNAL_METHOD;
    public static final Method COMPOSITE_SETTER_OBJECT_GET_INTERNAL_METHOD;
    public static final Method MULTIPLE_COMPOSITE_OBJECT_GET_INTERNAL_METHOD;
    public static final ImmutableSet<Method> INTEGER_GENERIC_FIELD_GETTER_GET_METHODS;
    public static final ImmutableSet<Method> LONG_GENERIC_FIELD_SETTER_SET_METHODS;
    public static final ImmutableSet<Method> STRING_FIELD_GETTER_OBJECT_GET_METHODS;
    public static final ImmutableSet<Method> STRING_FIELD_SETTER_OBJECT_SET_METHODS;
    public static final ImmutableSet<Method> DUPLICATE_NUMBER_FIELD_SET_METHOD_OBJECT_SET_METHODS;
    public static final ImmutableSet<Method> OBJECT_METHODS;
    public static final ImmutableSet<Method> INTEGER_GENERIC_FIELD_GETTER_METHODS;
    public static final ImmutableSet<Method> LONG_GENERIC_FIELD_SETTER_METHODS;
    public static final ImmutableSet<Method> STRING_FIELD_GET_METHOD_OBJECT_METHODS;
    public static final ImmutableSet<Method> STRING_FIELD_FLUENT_GET_METHOD_OBJECT_METHODS;
    public static final ImmutableSet<Method> STRING_FIELD_AND_STRING_FIELD_GET_METHOD_OBJECT_METHODS;
    public static final ImmutableSet<Method> STRING_FIELD_GETTER_OBJECT_METHODS;
    public static final ImmutableSet<Method> BOOLEAN_FIELD_IS_METHOD_OBJECT_METHODS;
    public static final ImmutableSet<Method> BOOLEAN_FIELD_GET_METHOD_OBJECT_METHODS;
    public static final ImmutableSet<Method> STRING_FIELD_SET_METHOD_OBJECT_METHODS;
    public static final ImmutableSet<Method> STRING_FIELD_FLUENT_SET_METHOD_OBJECT_METHODS;
    public static final ImmutableSet<Method> STRING_FIELD_AND_STRING_FIELD_SET_METHOD_OBJECT_METHODS;
    public static final ImmutableSet<Method> STRING_FIELD_CHAIN_SET_METHOD_OBJECT_METHODS;
    public static final ImmutableSet<Method> STRING_FIELD_SETTER_OBJECT_METHODS;
    public static final ImmutableSet<Method> DUPLICATE_NUMBER_FIELD_SET_METHOD_OBJECT_METHODS;
    public static final Constructor<NoFieldObject> NO_FIELD_OBJECT_CONSTRUCTOR;
    public static final Constructor<DoubleGenericFieldObject> DOUBLE_GENERIC_FIELD_OBJECT_CONSTRUCTOR;
    public static final Constructor<DuplicateNumberFieldSetMethodObject> DUPLICATE_NUMBER_FIELD_SET_METHOD_OBJECT_CONSTRUCTOR;
    public static final Constructor<FinalFieldObject> FINAL_FIELD_OBJECT_CONSTRUCTOR;
    public static final Constructor<GenericFieldObject> GENERIC_FIELD_OBJECT_CONSTRUCTOR;
    public static final Constructor<IntegerGenericFieldGetter> INTEGER_GENERIC_FIELD_GETTER_CONSTRUCTOR;
    public static final Constructor<LongGenericFieldSetter> LONG_GENERIC_FIELD_SETTER_CONSTRUCTOR;
    public static final Constructor<MultipleFieldObject> MULTIPLE_FIELD_OBJECT_CONSTRUCTOR;
    public static final Constructor<StaticFieldObject> STATIC_FIELD_OBJECT_CONSTRUCTOR;
    public static final Constructor<StringFieldObject> STRING_FIELD_OBJECT_CONSTRUCTOR;
    public static final Constructor<ChildrenLongFieldObject> CHILDREN_LONG_FIELD_OBJECT_CONSTRUCTOR;
    public static final Constructor<ChildrenSameNameFieldObject> CHILDREN_SAME_NAME_FIELD_OBJECT_CONSTRUCTOR;
    public static final Constructor<PrivateConstructObject> PRIVATE_CONSTRUCT_OBJECT_CONSTRUCTOR;
    public static final Constructor<ProtectedConstructObject> PROTECTED_CONSTRUCT_OBJECT_CONSTRUCTOR;
    public static final Constructor<ProtectedConstructChildrenObject> PROTECTED_CONSTRUCT_CHILDREN_OBJECT_CONSTRUCTOR;
    public static final ImmutableSet<Constructor<MultipleConstructObject>> MULTIPLE_CONSTRUCT_OBJECT_CONSTRUCTORS;
    public static final Constructor<StringFieldGetMethodObject> STRING_FIELD_GET_METHOD_OBJECT_CONSTRUCTOR;
    public static final Constructor<StringFieldFluentGetMethodObject> STRING_FIELD_FLUENT_GET_METHOD_OBJECT_CONSTRUCTOR;
    public static final Constructor<StringFieldAndStringFieldGetMethodObject> STRING_FIELD_AND_STRING_FIELD_GET_METHOD_OBJECT_CONSTRUCTOR;
    public static final Constructor<StringFieldGetterObject> STRING_FIELD_GETTER_OBJECT_CONSTRUCTOR;
    public static final Constructor<BooleanFieldIsMethodObject> BOOLEAN_FIELD_IS_METHOD_OBJECT_CONSTRUCTOR;
    public static final Constructor<BooleanFieldGetMethodObject> BOOLEAN_FIELD_GET_METHOD_OBJECT_CONSTRUCTOR;
    public static final Constructor<StringFieldSetMethodObject> STRING_FIELD_SET_METHOD_OBJECT_CONSTRUCTOR;
    public static final Constructor<StringFieldFluentSetMethodObject> STRING_FIELD_FLUENT_SET_METHOD_OBJECT_CONSTRUCTOR;
    public static final Constructor<StringFieldAndStringFieldSetMethodObject> STRING_FIELD_AND_STRING_FIELD_SET_METHOD_OBJECT_CONSTRUCTOR;
    public static final Constructor<StringFieldChainSetMethodObject> STRING_FIELD_CHAIN_SET_METHOD_OBJECT_CONSTRUCTOR;
    public static final Constructor<StringFieldSetterObject> STRING_FIELD_SETTER_OBJECT_CONSTRUCTOR;
    public static final ImmutableSet<Field> STRING_FIELD_OBJECT_FIELDS;
    public static final ImmutableSet<Field> CHILDREN_LONG_FIELD_OBJECT_FIELDS;
    public static final ImmutableSet<Field> CHILDREN_SAME_NAME_FIELD_OBJECT_FIELDS;
    public static final ImmutableSet<Field> DOUBLE_GENERIC_FIELD_OBJECT_FIELDS;
    public static final ImmutableSet<Field> FINAL_FIELD_OBJECT_FIELDS;
    public static final ImmutableSet<Field> STATIC_FIELD_OBJECT_FIELDS;
    public static final ImmutableSet<Field> MULTIPLE_FIELD_OBJECT_FIELDS;
    public static final PropertyReader<BooleanFieldGetMethodObject, Boolean> BOOLEAN_FIELD_GET_METHOD_OBJECT_BOOLEAN_FIELD_PROPERTY_READER;
    public static final PropertyReader<BooleanFieldIsMethodObject, Boolean> BOOLEAN_FIELD_IS_METHOD_OBJECT_BOOLEAN_FIELD_PROPERTY_READER;
    public static final PropertyAccessor<ChildrenLongFieldObject, String> CHILDREN_LONG_FIELD_OBJECT_STRING_FIELD_PROPERTY_ACCESSOR;
    public static final PropertyAccessor<ChildrenLongFieldObject, Long> CHILDREN_LONG_FIELD_OBJECT_LONG_FIELD_PROPERTY_ACCESSOR;
    public static final ImmutableSet<PropertyAccessor<ChildrenLongFieldObject, ?>> CHILDREN_LONG_FIELD_OBJECT_PROPERTY_ACCESSORS;
    public static final ImmutableSet<PropertyAccessor<ChildrenSameNameFieldObject, String>> CHILDREN_SAME_NAME_FIELD_OBJECT_PROPERTY_ACCESSORS;
    public static final PropertyAccessor<CompositeFieldObject, CompositeFieldObject.Internal> COMPOSITE_FIELD_OBJECT_INTERNAL_FIELD_PROPERTY_ACCESSOR;
    public static final PropertyReader<CompositeGetterObject, CompositeGetterObject.Internal> COMPOSITE_GETTER_OBJECT_INTERNAL_PROPERTY_READER;
    public static final PropertyReader<CompositeSetterObject, CompositeSetterObject.Internal> COMPOSITE_SETTER_OBJECT_INTERNAL_PROPERTY_READER;
    public static final PropertyAccessor<DoubleGenericFieldObject, Double> DOUBLE_GENERIC_FIELD_OBJECT_GENERIC_FIELD_PROPERTY_ACCESSOR;
    public static final ImmutableSet<PropertyWriter<DuplicateNumberFieldSetMethodObject, Number>> DUPLICATE_NUMBER_FIELD_SET_METHOD_OBJECT_PROPERTY_WRITERS;
    public static final PropertyAccessor<FinalFieldObject, String> FINAL_FIELD_OBJECT_STRING_FIELD_PROPERTY_ACCESSOR;
    public static final PropertyReader<GenericFieldGetter<Object>, Object> GENERIC_FIELD_GETTER_GENERIC_FIELD_PROPERTY_READER;
    public static final PropertyAccessor<GenericFieldObject<Object>, Object> GENERIC_FIELD_OBJECT_GENERIC_FIELD_PROPERTY_ACCESSOR;
    public static final PropertyWriter<GenericFieldSetter<Object>, Object> GENERIC_FIELD_SETTER_GENERIC_FIELD_PROPERTY_WRITER;
    public static final ImmutableSet<PropertyReader<IntegerGenericFieldGetter, Integer>> INTEGER_GENERIC_FIELD_GETTER_PROPERTY_READERS;
    public static final ImmutableSet<PropertyWriter<LongGenericFieldSetter, Long>> LONG_GENERIC_FIELD_SETTER_PROPERTY_WRITERS;
    public static final PropertyReader<MultipleCompositeObject, MultipleCompositeObject.Internal> MULTIPLE_COMPOSITE_OBJECT_INTERNAL_PROPERTY_READER;
    public static final PropertyAccessor<MultipleFieldObject, String> MULTIPLE_FIELD_OBJECT_STRING_FIELD_PROPERTY_ACCESSOR;
    public static final PropertyAccessor<MultipleFieldObject, Integer> MULTIPLE_FIELD_OBJECT_INTEGER_FIELD_PROPERTY_ACCESSOR;
    public static final PropertyAccessor<MultipleFieldObject, Integer> MULTIPLE_FIELD_OBJECT_INT_FIELD_PROPERTY_ACCESSOR;
    public static final PropertyAccessor<MultipleFieldObject, Boolean> MULTIPLE_FIELD_OBJECT_BOOLEAN_FIELD_PROPERTY_ACCESSOR;
    public static final ImmutableSet<PropertyAccessor<MultipleFieldObject, ?>> MULTIPLE_FIELD_OBJECT_PROPERTY_ACCESSORS;
    public static final PropertyAccessor<StringFieldAndStringFieldGetMethodObject, String> STRING_FIELD_AND_STRING_FIELD_GET_METHOD_OBJECT_STRING_FIELD_PROPERTY_ACCESSOR;
    public static final PropertyReader<StringFieldAndStringFieldGetMethodObject, String> STRING_FIELD_AND_STRING_FIELD_GET_METHOD_OBJECT_STRING_FIELD_GET_METHOD_PROPERTY_READER;
    public static final ImmutableSet<PropertyReader<StringFieldAndStringFieldGetMethodObject, String>> STRING_FIELD_AND_STRING_FIELD_GET_METHOD_OBJECT_PROPERTY_READERS;
    public static final PropertyAccessor<StringFieldAndStringFieldSetMethodObject, String> STRING_FIELD_AND_STRING_FIELD_SET_METHOD_OBJECT_STRING_FIELD_PROPERTY_ACCESSOR;
    public static final PropertyWriter<StringFieldAndStringFieldSetMethodObject, String> STRING_FIELD_AND_STRING_FIELD_SET_METHOD_OBJECT_SET_STRING_FIELD_METHOD_PROPERTY_WRITER;
    public static final ImmutableSet<PropertyWriter<StringFieldAndStringFieldSetMethodObject, String>> STRING_FIELD_AND_STRING_FIELD_SET_METHOD_OBJECT_PROPERTY_WRITERS;
    public static final PropertyWriter<StringFieldChainSetMethodObject, String> STRING_FIELD_CHAIN_SET_METHOD_OBJECT_SET_STRING_FIELD_METHOD_PROPERTY_WRITER;
    public static final PropertyReader<StringFieldFluentGetMethodObject, String> STRING_FIELD_FLUENT_GET_METHOD_OBJECT_STRING_FIELD_PROPERTY_READER;
    public static final PropertyWriter<StringFieldFluentSetMethodObject, String> STRING_FIELD_FLUENT_SET_METHOD_OBJECT_STRING_FIELD_METHOD_PROPERTY_WRITER;
    public static final PropertyReader<StringFieldGetMethodObject, String> STRING_FIELD_GET_METHOD_OBJECT_STRING_FIELD_PROPERTY_READER;
    public static final PropertyReader<StringFieldGetter, String> STRING_FIELD_GETTER_STRING_FIELD_PROPERTY_READER;
    public static final ImmutableSet<PropertyReader<StringFieldGetterObject, String>> STRING_FIELD_GETTER_OBJECT_PROPERTY_READERS;
    public static final PropertyAccessor<StringFieldObject, String> STRING_FIELD_OBJECT_STRING_FIELD_PROPERTY_ACCESSOR;
    public static final PropertyWriter<StringFieldSetMethodObject, String> STRING_FIELD_SET_METHOD_OBJECT_SET_STRING_FIELD_METHOD_PROPERTY_WRITER;
    public static final PropertyWriter<StringFieldSetter, String> STRING_FIELD_SETTER_SET_STRING_FIELD_METHOD_PROPERTY_WRITER;
    public static final ImmutableSet<PropertyWriter<StringFieldSetterObject, String>> STRING_FIELD_SETTER_OBJECT_PROPERTY_WRITERS;
    public static final ReadableProperty<BooleanFieldGetMethodObject, Boolean> BOOLEAN_FIELD_GET_METHOD_OBJECT_BOOLEAN_PROPERTY;
    public static final ReadableProperty<BooleanFieldIsMethodObject, Boolean> BOOLEAN_FIELD_IS_METHOD_OBJECT_BOOLEAN_PROPERTY;
    public static final AccessibleProperty<ChildrenLongFieldObject, String> CHILDREN_LONG_FIELD_OBJECT_STRING_PROPERTY;
    public static final AccessibleProperty<ChildrenLongFieldObject, Long> CHILDREN_LONG_FIELD_OBJECT_LONG_PROPERTY;
    public static final ImmutableSet<AccessibleProperty<ChildrenLongFieldObject, ?>> CHILDREN_LONG_FIELD_OBJECT_PROPERTIES;
    public static final AccessibleProperty<ChildrenSameNameFieldObject, String> CHILDREN_SAME_NAME_FIELD_OBJECT_STRING_PROPERTY;
    public static final AccessibleProperty<CompositeFieldObject, CompositeFieldObject.Internal> COMPOSITE_FIELD_OBJECT_INTERNAL_PROPERTY;
    public static final AccessibleProperty<CompositeFieldObject, Integer> COMPOSITE_FIELD_OBJECT_INTERNAL_INTEGER_PROPERTY;
    public static final ReadableProperty<CompositeGetterObject, CompositeGetterObject.Internal> COMPOSITE_GETTER_OBJECT_INTERNAL_PROPERTY;
    public static final ReadableProperty<CompositeGetterObject, Integer> COMPOSITE_GETTER_OBJECT_INTERNAL_INTEGER_PROPERTY;
    public static final ReadableProperty<CompositeSetterObject, CompositeSetterObject.Internal> COMPOSITE_SETTER_OBJECT_INTERNAL_PROPERTY;
    public static final WritableProperty<CompositeSetterObject, Integer> COMPOSITE_SETTER_OBJECT_INTERNAL_INTEGER_PROPERTY;
    public static final WritableProperty<DoubleGenericFieldObject, Double> DOUBLE_GENERIC_FIELD_OBJECT_GENERIC_PROPERTY;
    public static final WritableProperty<DuplicateNumberFieldSetMethodObject, Number> DUPLICATE_NUMBER_FIELD_SET_METHOD_OBJECT_NUMBER_PROPERTY;
    public static final AccessibleProperty<FinalFieldObject, String> FINAL_FIELD_OBJECT_STRING_PROPERTY;
    public static final ReadableProperty<GenericFieldGetter<Object>, Object> GENERIC_FIELD_GETTER_GENERIC_PROPERTY;
    public static final AccessibleProperty<GenericFieldObject<Object>, Object> GENERIC_FIELD_OBJECT_GENERIC_PROPERTY;
    public static final WritableProperty<GenericFieldSetter<Object>, Object> GENERIC_FIELD_SETTER_GENERIC_PROPERTY;
    public static final ReadableProperty<IntegerGenericFieldGetter, Integer> INTEGER_GENERIC_FIELD_GETTER_GENERIC_PROPERTY;
    public static final WritableProperty<LongGenericFieldSetter, Long> LONG_GENERIC_FIELD_SETTER_GENERIC_PROPERTY;
    public static final ReadableProperty<MultipleCompositeObject, MultipleCompositeObject.Internal> MULTIPLE_COMPOSITE_OBJECT_INTERNAL_PROPERTY;
    public static final AccessibleProperty<MultipleCompositeObject, MultipleCompositeObject.Internal> MULTIPLE_COMPOSITE_OBJECT_INTERNAL_INTERNAL_PROPERTY;
    public static final AccessibleProperty<MultipleCompositeObject, MultipleCompositeObject.Internal> MULTIPLE_COMPOSITE_OBJECT_MULTIPLE_INTERNAL_PROPERTY;
    public static final AccessibleProperty<MultipleFieldObject, String> MULTIPLE_FIELD_OBJECT_STRING_PROPERTY;
    public static final AccessibleProperty<MultipleFieldObject, Integer> MULTIPLE_FIELD_OBJECT_INTEGER_PROPERTY;
    public static final AccessibleProperty<MultipleFieldObject, Integer> MULTIPLE_FIELD_OBJECT_INT_PROPERTY;
    public static final AccessibleProperty<MultipleFieldObject, Boolean> MULTIPLE_FIELD_OBJECT_BOOLEAN_PROPERTY;
    public static final ImmutableSet<AccessibleProperty<MultipleFieldObject, ?>> MULTIPLE_FIELD_OBJECT_PROPERTIES;
    public static final AccessibleProperty<StringFieldAndStringFieldGetMethodObject, String> STRING_FIELD_AND_STRING_FIELD_GET_METHOD_OBJECT_STRING_PROPERTY;
    public static final AccessibleProperty<StringFieldAndStringFieldSetMethodObject, String> STRING_FIELD_AND_STRING_FIELD_SET_METHOD_OBJECT_STRING_PROPERTY;
    public static final WritableProperty<StringFieldChainSetMethodObject, String> STRING_FIELD_CHAIN_SET_METHOD_OBJECT_STRING_PROPERTY;
    public static final ReadableProperty<StringFieldFluentGetMethodObject, String> STRING_FIELD_FLUENT_GET_METHOD_OBJECT_STRING_PROPERTY;
    public static final WritableProperty<StringFieldFluentSetMethodObject, String> STRING_FIELD_FLUENT_SET_METHOD_OBJECT_STRING_PROPERTY;
    public static final ReadableProperty<StringFieldGetMethodObject, String> STRING_FIELD_GET_METHOD_OBJECT_STRING_PROPERTY;
    public static final ReadableProperty<StringFieldGetter, String> STRING_FIELD_GETTER_STRING_PROPERTY;
    public static final ReadableProperty<StringFieldGetterObject, String> STRING_FIELD_GETTER_OBJECT_STRING_PROPERTY;
    public static final AccessibleProperty<StringFieldObject, String> STRING_FIELD_OBJECT_STRING_PROPERTY;
    public static final WritableProperty<StringFieldSetMethodObject, String> STRING_FIELD_SET_METHOD_OBJECT_STRING_PROPERTY;
    public static final WritableProperty<StringFieldSetter, String> STRING_FIELD_SETTER_STRING_PROPERTY;
    public static final WritableProperty<StringFieldSetterObject, String> STRING_FIELD_SETTER_OBJECT_STRING_PROPERTY;

    static {
        try {
            STRING_FIELD_OBJECT_STRING_FIELD = StringFieldObject.class.getDeclaredField(StringFieldObject.Fields.STRING_FIELD);
            FINAL_FIELD_OBJECT_STRING_FIELD = FinalFieldObject.class.getDeclaredField(FinalFieldObject.Fields.STRING_FIELD);
            GENERIC_FIELD_OBJECT_GENERIC_FIELD = GenericFieldObject.class.getDeclaredField(GenericFieldObject.Fields.GENERIC_FIELD);
            STATIC_FIELD_OBJECT_STRING_FIELD = StaticFieldObject.class.getDeclaredField("stringField");
            CHILDREN_LONG_FIELD_OBJECT_LONG_FIELD = ChildrenLongFieldObject.class.getDeclaredField(ChildrenLongFieldObject.Fields.LONG_FIELD);
            CHILDREN_SAME_NAME_FIELD_OBJECT_STRING_FIELD = ChildrenSameNameFieldObject.class.getDeclaredField(ChildrenSameNameFieldObject.Fields.STRING_FIELD);
            COMPOSITE_FIELD_OBJECT_INTERNAL_FIELD = CompositeFieldObject.class.getDeclaredField(CompositeFieldObject.Fields.INTERNAL);
            MULTIPLE_FIELD_OBJECT_STRING_FIELD = MultipleFieldObject.class.getDeclaredField(MultipleFieldObject.Fields.STRING_FIELD);
            MULTIPLE_FIELD_OBJECT_INTEGER_FIELD = MultipleFieldObject.class.getDeclaredField(MultipleFieldObject.Fields.INTEGER_FIELD);
            MULTIPLE_FIELD_OBJECT_INT_FIELD = MultipleFieldObject.class.getDeclaredField(MultipleFieldObject.Fields.INT_FIELD);
            MULTIPLE_FIELD_OBJECT_BOOLEAN_FIELD = MultipleFieldObject.class.getDeclaredField(MultipleFieldObject.Fields.BOOLEAN_FIELD);
            STRING_FIELD_AND_STRING_FIELD_GET_METHOD_OBJECT_STRING_FIELD = StringFieldAndStringFieldGetMethodObject.class.getDeclaredField(StringFieldAndStringFieldGetMethodObject.Fields.STRING_FIELD);
            STRING_FIELD_AND_STRING_FIELD_SET_METHOD_OBJECT_STRING_FIELD = StringFieldAndStringFieldSetMethodObject.class.getDeclaredField(StringFieldAndStringFieldSetMethodObject.Fields.STRING_FIELD);
            GENERIC_FIELD_GETTER_GET_GENERIC_FIELD_METHOD = GenericFieldGetter.class.getDeclaredMethod("getGenericField");
            GENERIC_FIELD_SETTER_SET_GENERIC_FIELD_METHOD = GenericFieldSetter.class.getDeclaredMethod("setGenericField", Object.class);
            INTEGER_GENERIC_FIELD_GETTER_GET_GENERIC_FIELD_METHOD = IntegerGenericFieldGetter.class.getDeclaredMethod("getGenericField");
            INTEGER_GENERIC_FIELD_GETTER_BRIDGE_GET_GENERIC_FIELD_METHOD = Arrays.stream(IntegerGenericFieldGetter.class.getDeclaredMethods()).filter(Method::isBridge).findAny().orElseThrow(AssertionError::new);
            LONG_GENERIC_FIELD_SETTER_SET_GENERIC_FIELD_METHOD = LongGenericFieldSetter.class.getDeclaredMethod("setGenericField", Long.class);
            LONG_GENERIC_FIELD_SETTER_BRIDGE_SET_GENERIC_FIELD_METHOD = Arrays.stream(LongGenericFieldSetter.class.getDeclaredMethods()).filter(Method::isBridge).findAny().orElseThrow(AssertionError::new);
            STRING_FIELD_GET_METHOD_OBJECT_GET_STRING_FIELD_METHOD = StringFieldGetMethodObject.class.getDeclaredMethod("getStringField");
            STRING_FIELD_FLUENT_GET_METHOD_OBJECT_STRING_FIELD_METHOD = StringFieldFluentGetMethodObject.class.getDeclaredMethod("stringField");
            STRING_FIELD_AND_STRING_FIELD_GET_METHOD_OBJECT_GET_STRING_FIELD_METHOD = StringFieldAndStringFieldGetMethodObject.class.getDeclaredMethod("getStringField");
            STRING_FIELD_GETTER_GET_STRING_FIELD_METHOD = StringFieldGetter.class.getDeclaredMethod("getStringField");
            STRING_FIELD_GETTER_OBJECT_GET_STRING_FIELD_METHOD = StringFieldGetterObject.class.getDeclaredMethod("getStringField");
            BOOLEAN_FIELD_IS_METHOD_OBJECT_IS_BOOLEAN_FIELD_METHOD = BooleanFieldIsMethodObject.class.getDeclaredMethod("isBooleanField");
            BOOLEAN_FIELD_GET_METHOD_OBJECT_GET_BOOLEAN_FIELD_METHOD = BooleanFieldGetMethodObject.class.getDeclaredMethod("getBooleanField");
            STRING_FIELD_SET_METHOD_OBJECT_SET_STRING_FIELD_METHOD = StringFieldSetMethodObject.class.getDeclaredMethod("setStringField", String.class);
            STRING_FIELD_FLUENT_SET_METHOD_OBJECT_STRING_FIELD_METHOD = StringFieldFluentSetMethodObject.class.getDeclaredMethod("stringField", String.class);
            STRING_FIELD_AND_STRING_FIELD_SET_METHOD_OBJECT_SET_STRING_FIELD_METHOD = StringFieldAndStringFieldSetMethodObject.class.getDeclaredMethod("setStringField", String.class);
            STRING_FIELD_SETTER_SET_STRING_FIELD_METHOD = StringFieldSetter.class.getDeclaredMethod("setStringField", String.class);
            STRING_FIELD_SETTER_OBJECT_SET_STRING_FIELD_METHOD = StringFieldSetterObject.class.getDeclaredMethod("setStringField", String.class);
            STRING_FIELD_CHAIN_SET_METHOD_OBJECT_SET_STRING_FIELD_METHOD = StringFieldChainSetMethodObject.class.getDeclaredMethod("setStringField", String.class);
            DUPLICATE_NUMBER_FIELD_SET_METHOD_OBJECT_NUMBER_SET_NUMBER_FIELD_METHOD = DuplicateNumberFieldSetMethodObject.class.getDeclaredMethod("setNumberField", Number.class);
            DUPLICATE_NUMBER_FIELD_SET_METHOD_OBJECT_INT_SET_NUMBER_FIELD_METHOD = DuplicateNumberFieldSetMethodObject.class.getDeclaredMethod("setNumberField", int.class);
            COMPOSITE_GETTER_OBJECT_GET_INTERNAL_METHOD = CompositeGetterObject.class.getDeclaredMethod("getInternal");
            COMPOSITE_SETTER_OBJECT_GET_INTERNAL_METHOD = CompositeSetterObject.class.getDeclaredMethod("getInternal");
            MULTIPLE_COMPOSITE_OBJECT_GET_INTERNAL_METHOD = MultipleCompositeObject.class.getDeclaredMethod("getInternal");
            INTEGER_GENERIC_FIELD_GETTER_GET_METHODS = ImmutableSet.of(GENERIC_FIELD_GETTER_GET_GENERIC_FIELD_METHOD, INTEGER_GENERIC_FIELD_GETTER_GET_GENERIC_FIELD_METHOD, INTEGER_GENERIC_FIELD_GETTER_BRIDGE_GET_GENERIC_FIELD_METHOD);
            LONG_GENERIC_FIELD_SETTER_SET_METHODS = ImmutableSet.of(GENERIC_FIELD_SETTER_SET_GENERIC_FIELD_METHOD, LONG_GENERIC_FIELD_SETTER_SET_GENERIC_FIELD_METHOD, LONG_GENERIC_FIELD_SETTER_BRIDGE_SET_GENERIC_FIELD_METHOD);
            STRING_FIELD_GETTER_OBJECT_GET_METHODS = ImmutableSet.of(STRING_FIELD_GETTER_GET_STRING_FIELD_METHOD, STRING_FIELD_GETTER_OBJECT_GET_STRING_FIELD_METHOD);
            STRING_FIELD_SETTER_OBJECT_SET_METHODS = ImmutableSet.of(STRING_FIELD_SETTER_SET_STRING_FIELD_METHOD, STRING_FIELD_SETTER_OBJECT_SET_STRING_FIELD_METHOD);
            DUPLICATE_NUMBER_FIELD_SET_METHOD_OBJECT_SET_METHODS = ImmutableSet.of(DUPLICATE_NUMBER_FIELD_SET_METHOD_OBJECT_NUMBER_SET_NUMBER_FIELD_METHOD, DUPLICATE_NUMBER_FIELD_SET_METHOD_OBJECT_INT_SET_NUMBER_FIELD_METHOD);
            OBJECT_METHODS = Arrays.stream(Object.class.getDeclaredMethods()).collect(ImmutableSet.toImmutableSet());
            INTEGER_GENERIC_FIELD_GETTER_METHODS = Stream.concat(OBJECT_METHODS.stream(), Stream.of(GENERIC_FIELD_GETTER_GET_GENERIC_FIELD_METHOD, INTEGER_GENERIC_FIELD_GETTER_GET_GENERIC_FIELD_METHOD, INTEGER_GENERIC_FIELD_GETTER_BRIDGE_GET_GENERIC_FIELD_METHOD)).collect(ImmutableSet.toImmutableSet());
            LONG_GENERIC_FIELD_SETTER_METHODS = Stream.concat(OBJECT_METHODS.stream(), Stream.of(GENERIC_FIELD_SETTER_SET_GENERIC_FIELD_METHOD, LONG_GENERIC_FIELD_SETTER_SET_GENERIC_FIELD_METHOD, LONG_GENERIC_FIELD_SETTER_BRIDGE_SET_GENERIC_FIELD_METHOD)).collect(ImmutableSet.toImmutableSet());
            STRING_FIELD_GET_METHOD_OBJECT_METHODS = Stream.concat(OBJECT_METHODS.stream(), Stream.of(STRING_FIELD_GET_METHOD_OBJECT_GET_STRING_FIELD_METHOD)).collect(ImmutableSet.toImmutableSet());
            STRING_FIELD_FLUENT_GET_METHOD_OBJECT_METHODS = Stream.concat(OBJECT_METHODS.stream(), Stream.of(STRING_FIELD_FLUENT_GET_METHOD_OBJECT_STRING_FIELD_METHOD)).collect(ImmutableSet.toImmutableSet());
            STRING_FIELD_AND_STRING_FIELD_GET_METHOD_OBJECT_METHODS = Stream.concat(OBJECT_METHODS.stream(), Stream.of(STRING_FIELD_AND_STRING_FIELD_GET_METHOD_OBJECT_GET_STRING_FIELD_METHOD)).collect(ImmutableSet.toImmutableSet());
            STRING_FIELD_GETTER_OBJECT_METHODS = Stream.concat(OBJECT_METHODS.stream(), Stream.of(STRING_FIELD_GETTER_GET_STRING_FIELD_METHOD, STRING_FIELD_GETTER_OBJECT_GET_STRING_FIELD_METHOD)).collect(ImmutableSet.toImmutableSet());
            BOOLEAN_FIELD_IS_METHOD_OBJECT_METHODS = Stream.concat(OBJECT_METHODS.stream(), Stream.of(BOOLEAN_FIELD_IS_METHOD_OBJECT_IS_BOOLEAN_FIELD_METHOD)).collect(ImmutableSet.toImmutableSet());
            BOOLEAN_FIELD_GET_METHOD_OBJECT_METHODS = Stream.concat(OBJECT_METHODS.stream(), Stream.of(BOOLEAN_FIELD_GET_METHOD_OBJECT_GET_BOOLEAN_FIELD_METHOD)).collect(ImmutableSet.toImmutableSet());
            STRING_FIELD_SET_METHOD_OBJECT_METHODS = Stream.concat(OBJECT_METHODS.stream(), Stream.of(STRING_FIELD_SET_METHOD_OBJECT_SET_STRING_FIELD_METHOD)).collect(ImmutableSet.toImmutableSet());
            STRING_FIELD_FLUENT_SET_METHOD_OBJECT_METHODS = Stream.concat(OBJECT_METHODS.stream(), Stream.of(STRING_FIELD_FLUENT_SET_METHOD_OBJECT_STRING_FIELD_METHOD)).collect(ImmutableSet.toImmutableSet());
            STRING_FIELD_AND_STRING_FIELD_SET_METHOD_OBJECT_METHODS = Stream.concat(OBJECT_METHODS.stream(), Stream.of(STRING_FIELD_AND_STRING_FIELD_SET_METHOD_OBJECT_SET_STRING_FIELD_METHOD)).collect(ImmutableSet.toImmutableSet());
            STRING_FIELD_CHAIN_SET_METHOD_OBJECT_METHODS = Stream.concat(OBJECT_METHODS.stream(), Stream.of(STRING_FIELD_CHAIN_SET_METHOD_OBJECT_SET_STRING_FIELD_METHOD)).collect(ImmutableSet.toImmutableSet());
            STRING_FIELD_SETTER_OBJECT_METHODS = Stream.concat(OBJECT_METHODS.stream(), Stream.of(STRING_FIELD_SETTER_SET_STRING_FIELD_METHOD, STRING_FIELD_SETTER_OBJECT_SET_STRING_FIELD_METHOD)).collect(ImmutableSet.toImmutableSet());
            DUPLICATE_NUMBER_FIELD_SET_METHOD_OBJECT_METHODS = Stream.concat(OBJECT_METHODS.stream(), DUPLICATE_NUMBER_FIELD_SET_METHOD_OBJECT_SET_METHODS.stream()).collect(ImmutableSet.toImmutableSet());
            NO_FIELD_OBJECT_CONSTRUCTOR = NoFieldObject.class.getDeclaredConstructor();
            DOUBLE_GENERIC_FIELD_OBJECT_CONSTRUCTOR = DoubleGenericFieldObject.class.getDeclaredConstructor();
            DUPLICATE_NUMBER_FIELD_SET_METHOD_OBJECT_CONSTRUCTOR = DuplicateNumberFieldSetMethodObject.class.getDeclaredConstructor();
            FINAL_FIELD_OBJECT_CONSTRUCTOR = FinalFieldObject.class.getDeclaredConstructor();
            GENERIC_FIELD_OBJECT_CONSTRUCTOR = GenericFieldObject.class.getDeclaredConstructor();
            INTEGER_GENERIC_FIELD_GETTER_CONSTRUCTOR = IntegerGenericFieldGetter.class.getDeclaredConstructor();
            LONG_GENERIC_FIELD_SETTER_CONSTRUCTOR = LongGenericFieldSetter.class.getDeclaredConstructor();
            MULTIPLE_FIELD_OBJECT_CONSTRUCTOR = MultipleFieldObject.class.getDeclaredConstructor();
            STATIC_FIELD_OBJECT_CONSTRUCTOR = StaticFieldObject.class.getDeclaredConstructor();
            STRING_FIELD_OBJECT_CONSTRUCTOR = StringFieldObject.class.getDeclaredConstructor();
            CHILDREN_LONG_FIELD_OBJECT_CONSTRUCTOR = ChildrenLongFieldObject.class.getDeclaredConstructor();
            CHILDREN_SAME_NAME_FIELD_OBJECT_CONSTRUCTOR = ChildrenSameNameFieldObject.class.getDeclaredConstructor();
            PRIVATE_CONSTRUCT_OBJECT_CONSTRUCTOR = PrivateConstructObject.class.getDeclaredConstructor(String.class, Integer.class, int.class, boolean.class);
            PROTECTED_CONSTRUCT_OBJECT_CONSTRUCTOR = ProtectedConstructObject.class.getDeclaredConstructor(String.class, Integer.class, int.class, boolean.class);
            PROTECTED_CONSTRUCT_CHILDREN_OBJECT_CONSTRUCTOR = ProtectedConstructChildrenObject.class.getConstructor(String.class, Integer.class, int.class, boolean.class);
            //noinspection unchecked
            MULTIPLE_CONSTRUCT_OBJECT_CONSTRUCTORS = Arrays.stream(MultipleConstructObject.class.getDeclaredConstructors()).map(c -> (Constructor<MultipleConstructObject>) c).collect(ImmutableSet.toImmutableSet());
            STRING_FIELD_GET_METHOD_OBJECT_CONSTRUCTOR = StringFieldGetMethodObject.class.getDeclaredConstructor();
            STRING_FIELD_FLUENT_GET_METHOD_OBJECT_CONSTRUCTOR = StringFieldFluentGetMethodObject.class.getDeclaredConstructor();
            STRING_FIELD_AND_STRING_FIELD_GET_METHOD_OBJECT_CONSTRUCTOR = StringFieldAndStringFieldGetMethodObject.class.getDeclaredConstructor();
            STRING_FIELD_GETTER_OBJECT_CONSTRUCTOR = StringFieldGetterObject.class.getDeclaredConstructor();
            BOOLEAN_FIELD_IS_METHOD_OBJECT_CONSTRUCTOR = BooleanFieldIsMethodObject.class.getDeclaredConstructor();
            BOOLEAN_FIELD_GET_METHOD_OBJECT_CONSTRUCTOR = BooleanFieldGetMethodObject.class.getDeclaredConstructor();
            STRING_FIELD_SET_METHOD_OBJECT_CONSTRUCTOR = StringFieldSetMethodObject.class.getDeclaredConstructor();
            STRING_FIELD_FLUENT_SET_METHOD_OBJECT_CONSTRUCTOR = StringFieldFluentSetMethodObject.class.getDeclaredConstructor();
            STRING_FIELD_AND_STRING_FIELD_SET_METHOD_OBJECT_CONSTRUCTOR = StringFieldAndStringFieldSetMethodObject.class.getDeclaredConstructor();
            STRING_FIELD_CHAIN_SET_METHOD_OBJECT_CONSTRUCTOR = StringFieldChainSetMethodObject.class.getDeclaredConstructor();
            STRING_FIELD_SETTER_OBJECT_CONSTRUCTOR = StringFieldSetterObject.class.getDeclaredConstructor();
            STRING_FIELD_OBJECT_FIELDS = ImmutableSet.of(STRING_FIELD_OBJECT_STRING_FIELD);
            CHILDREN_LONG_FIELD_OBJECT_FIELDS = ImmutableSet.<Field>builder().addAll(STRING_FIELD_OBJECT_FIELDS).add(CHILDREN_LONG_FIELD_OBJECT_LONG_FIELD).build();
            CHILDREN_SAME_NAME_FIELD_OBJECT_FIELDS = ImmutableSet.<Field>builder().addAll(STRING_FIELD_OBJECT_FIELDS).add(CHILDREN_SAME_NAME_FIELD_OBJECT_STRING_FIELD).build();
            DOUBLE_GENERIC_FIELD_OBJECT_FIELDS = ImmutableSet.of(GENERIC_FIELD_OBJECT_GENERIC_FIELD);
            FINAL_FIELD_OBJECT_FIELDS = ImmutableSet.of(FINAL_FIELD_OBJECT_STRING_FIELD);
            STATIC_FIELD_OBJECT_FIELDS = ImmutableSet.of(STATIC_FIELD_OBJECT_STRING_FIELD);
            MULTIPLE_FIELD_OBJECT_FIELDS = ImmutableSet.of(MULTIPLE_FIELD_OBJECT_STRING_FIELD, MULTIPLE_FIELD_OBJECT_INTEGER_FIELD, MULTIPLE_FIELD_OBJECT_INT_FIELD, MULTIPLE_FIELD_OBJECT_BOOLEAN_FIELD);
            BOOLEAN_FIELD_GET_METHOD_OBJECT_BOOLEAN_FIELD_PROPERTY_READER = PropertyReader.from(BooleanFieldGetMethodObject.class, BOOLEAN_FIELD_GET_METHOD_OBJECT_GET_BOOLEAN_FIELD_METHOD, "booleanField");
            BOOLEAN_FIELD_IS_METHOD_OBJECT_BOOLEAN_FIELD_PROPERTY_READER = PropertyReader.from(BooleanFieldIsMethodObject.class, BOOLEAN_FIELD_IS_METHOD_OBJECT_IS_BOOLEAN_FIELD_METHOD, "booleanField");
            CHILDREN_LONG_FIELD_OBJECT_STRING_FIELD_PROPERTY_ACCESSOR = PropertyAccessor.from(ChildrenLongFieldObject.class, STRING_FIELD_OBJECT_STRING_FIELD);
            CHILDREN_LONG_FIELD_OBJECT_LONG_FIELD_PROPERTY_ACCESSOR = PropertyAccessor.from(ChildrenLongFieldObject.class, CHILDREN_LONG_FIELD_OBJECT_LONG_FIELD);
            CHILDREN_LONG_FIELD_OBJECT_PROPERTY_ACCESSORS = ImmutableSet.of(CHILDREN_LONG_FIELD_OBJECT_STRING_FIELD_PROPERTY_ACCESSOR, CHILDREN_LONG_FIELD_OBJECT_LONG_FIELD_PROPERTY_ACCESSOR);
            CHILDREN_SAME_NAME_FIELD_OBJECT_PROPERTY_ACCESSORS = CHILDREN_SAME_NAME_FIELD_OBJECT_FIELDS.stream().map(field -> PropertyAccessor.<ChildrenSameNameFieldObject, String>from(TypeToken.of(ChildrenSameNameFieldObject.class), field)).collect(ImmutableSet.toImmutableSet());
            COMPOSITE_FIELD_OBJECT_INTERNAL_FIELD_PROPERTY_ACCESSOR = PropertyAccessor.from(CompositeFieldObject.class, COMPOSITE_FIELD_OBJECT_INTERNAL_FIELD);
            COMPOSITE_GETTER_OBJECT_INTERNAL_PROPERTY_READER = PropertyReader.from(CompositeGetterObject.class, COMPOSITE_GETTER_OBJECT_GET_INTERNAL_METHOD, "internal");
            COMPOSITE_SETTER_OBJECT_INTERNAL_PROPERTY_READER = PropertyReader.from(CompositeSetterObject.class, COMPOSITE_SETTER_OBJECT_GET_INTERNAL_METHOD, "internal");
            DOUBLE_GENERIC_FIELD_OBJECT_GENERIC_FIELD_PROPERTY_ACCESSOR = PropertyAccessor.from(DoubleGenericFieldObject.class, GENERIC_FIELD_OBJECT_GENERIC_FIELD);
            DUPLICATE_NUMBER_FIELD_SET_METHOD_OBJECT_PROPERTY_WRITERS = DUPLICATE_NUMBER_FIELD_SET_METHOD_OBJECT_SET_METHODS.stream().map(method -> PropertyWriter.<DuplicateNumberFieldSetMethodObject, Number>from(TypeToken.of(DuplicateNumberFieldSetMethodObject.class), method, "numberField")).collect(ImmutableSet.toImmutableSet());
            FINAL_FIELD_OBJECT_STRING_FIELD_PROPERTY_ACCESSOR = PropertyAccessor.from(FinalFieldObject.class, FINAL_FIELD_OBJECT_STRING_FIELD);
            GENERIC_FIELD_GETTER_GENERIC_FIELD_PROPERTY_READER = PropertyReader.from(new TypeToken<GenericFieldGetter<Object>>() {
            }, GENERIC_FIELD_GETTER_GET_GENERIC_FIELD_METHOD, "genericField");
            GENERIC_FIELD_OBJECT_GENERIC_FIELD_PROPERTY_ACCESSOR = PropertyAccessor.from(new TypeToken<GenericFieldObject<Object>>() {
            }, GENERIC_FIELD_OBJECT_GENERIC_FIELD);
            GENERIC_FIELD_SETTER_GENERIC_FIELD_PROPERTY_WRITER = PropertyWriter.from(new TypeToken<GenericFieldSetter<Object>>() {
            }, GENERIC_FIELD_SETTER_SET_GENERIC_FIELD_METHOD, "genericField");
            INTEGER_GENERIC_FIELD_GETTER_PROPERTY_READERS = INTEGER_GENERIC_FIELD_GETTER_GET_METHODS.stream().map(method -> PropertyReader.<IntegerGenericFieldGetter, Integer>from(IntegerGenericFieldGetter.class, method, "genericField")).collect(ImmutableSet.toImmutableSet());
            LONG_GENERIC_FIELD_SETTER_PROPERTY_WRITERS = LONG_GENERIC_FIELD_SETTER_SET_METHODS.stream().map(method -> PropertyWriter.<LongGenericFieldSetter, Long>from(LongGenericFieldSetter.class, method, "genericField")).collect(ImmutableSet.toImmutableSet());
            MULTIPLE_COMPOSITE_OBJECT_INTERNAL_PROPERTY_READER = PropertyReader.from(MultipleCompositeObject.class, MULTIPLE_COMPOSITE_OBJECT_GET_INTERNAL_METHOD, "internal");
            MULTIPLE_FIELD_OBJECT_STRING_FIELD_PROPERTY_ACCESSOR = PropertyAccessor.from(MultipleFieldObject.class, MULTIPLE_FIELD_OBJECT_STRING_FIELD);
            MULTIPLE_FIELD_OBJECT_INTEGER_FIELD_PROPERTY_ACCESSOR = PropertyAccessor.from(MultipleFieldObject.class, MULTIPLE_FIELD_OBJECT_INTEGER_FIELD);
            MULTIPLE_FIELD_OBJECT_INT_FIELD_PROPERTY_ACCESSOR = PropertyAccessor.from(MultipleFieldObject.class, MULTIPLE_FIELD_OBJECT_INT_FIELD);
            MULTIPLE_FIELD_OBJECT_BOOLEAN_FIELD_PROPERTY_ACCESSOR = PropertyAccessor.from(MultipleFieldObject.class, MULTIPLE_FIELD_OBJECT_BOOLEAN_FIELD);
            MULTIPLE_FIELD_OBJECT_PROPERTY_ACCESSORS = ImmutableSet.of(MULTIPLE_FIELD_OBJECT_STRING_FIELD_PROPERTY_ACCESSOR, MULTIPLE_FIELD_OBJECT_INTEGER_FIELD_PROPERTY_ACCESSOR, MULTIPLE_FIELD_OBJECT_INT_FIELD_PROPERTY_ACCESSOR, MULTIPLE_FIELD_OBJECT_BOOLEAN_FIELD_PROPERTY_ACCESSOR);
            STRING_FIELD_AND_STRING_FIELD_GET_METHOD_OBJECT_STRING_FIELD_PROPERTY_ACCESSOR = PropertyAccessor.from(StringFieldAndStringFieldGetMethodObject.class, STRING_FIELD_AND_STRING_FIELD_GET_METHOD_OBJECT_STRING_FIELD);
            STRING_FIELD_AND_STRING_FIELD_GET_METHOD_OBJECT_STRING_FIELD_GET_METHOD_PROPERTY_READER = PropertyReader.from(StringFieldAndStringFieldGetMethodObject.class, STRING_FIELD_AND_STRING_FIELD_GET_METHOD_OBJECT_GET_STRING_FIELD_METHOD, StringFieldAndStringFieldGetMethodObject.Fields.STRING_FIELD);
            STRING_FIELD_AND_STRING_FIELD_GET_METHOD_OBJECT_PROPERTY_READERS = ImmutableSet.of(STRING_FIELD_AND_STRING_FIELD_GET_METHOD_OBJECT_STRING_FIELD_PROPERTY_ACCESSOR, STRING_FIELD_AND_STRING_FIELD_GET_METHOD_OBJECT_STRING_FIELD_GET_METHOD_PROPERTY_READER);
            STRING_FIELD_AND_STRING_FIELD_SET_METHOD_OBJECT_STRING_FIELD_PROPERTY_ACCESSOR = PropertyAccessor.from(StringFieldAndStringFieldSetMethodObject.class, STRING_FIELD_AND_STRING_FIELD_SET_METHOD_OBJECT_STRING_FIELD);
            STRING_FIELD_AND_STRING_FIELD_SET_METHOD_OBJECT_SET_STRING_FIELD_METHOD_PROPERTY_WRITER = PropertyWriter.from(StringFieldAndStringFieldSetMethodObject.class, STRING_FIELD_AND_STRING_FIELD_SET_METHOD_OBJECT_SET_STRING_FIELD_METHOD, StringFieldAndStringFieldSetMethodObject.Fields.STRING_FIELD);
            STRING_FIELD_AND_STRING_FIELD_SET_METHOD_OBJECT_PROPERTY_WRITERS = ImmutableSet.of(STRING_FIELD_AND_STRING_FIELD_SET_METHOD_OBJECT_STRING_FIELD_PROPERTY_ACCESSOR, STRING_FIELD_AND_STRING_FIELD_SET_METHOD_OBJECT_SET_STRING_FIELD_METHOD_PROPERTY_WRITER);
            STRING_FIELD_CHAIN_SET_METHOD_OBJECT_SET_STRING_FIELD_METHOD_PROPERTY_WRITER = PropertyWriter.from(StringFieldChainSetMethodObject.class, STRING_FIELD_CHAIN_SET_METHOD_OBJECT_SET_STRING_FIELD_METHOD, "stringField");
            STRING_FIELD_FLUENT_GET_METHOD_OBJECT_STRING_FIELD_PROPERTY_READER = PropertyReader.from(StringFieldFluentGetMethodObject.class, STRING_FIELD_FLUENT_GET_METHOD_OBJECT_STRING_FIELD_METHOD, "stringField");
            STRING_FIELD_FLUENT_SET_METHOD_OBJECT_STRING_FIELD_METHOD_PROPERTY_WRITER = PropertyWriter.from(StringFieldFluentSetMethodObject.class, STRING_FIELD_FLUENT_SET_METHOD_OBJECT_STRING_FIELD_METHOD, "stringField");
            STRING_FIELD_GET_METHOD_OBJECT_STRING_FIELD_PROPERTY_READER = PropertyReader.from(StringFieldGetMethodObject.class, STRING_FIELD_GET_METHOD_OBJECT_GET_STRING_FIELD_METHOD, "stringField");
            STRING_FIELD_GETTER_STRING_FIELD_PROPERTY_READER = PropertyReader.from(StringFieldGetter.class, STRING_FIELD_GETTER_GET_STRING_FIELD_METHOD, "stringField");
            STRING_FIELD_GETTER_OBJECT_PROPERTY_READERS = STRING_FIELD_GETTER_OBJECT_GET_METHODS.stream().map(method -> PropertyReader.<StringFieldGetterObject, String>from(StringFieldGetterObject.class, method, "stringField")).collect(ImmutableSet.toImmutableSet());
            STRING_FIELD_OBJECT_STRING_FIELD_PROPERTY_ACCESSOR = PropertyAccessor.from(StringFieldObject.class, STRING_FIELD_OBJECT_STRING_FIELD);
            STRING_FIELD_SET_METHOD_OBJECT_SET_STRING_FIELD_METHOD_PROPERTY_WRITER = PropertyWriter.from(StringFieldSetMethodObject.class, STRING_FIELD_SET_METHOD_OBJECT_SET_STRING_FIELD_METHOD, "stringField");
            STRING_FIELD_SETTER_SET_STRING_FIELD_METHOD_PROPERTY_WRITER = PropertyWriter.from(StringFieldSetter.class, STRING_FIELD_SETTER_SET_STRING_FIELD_METHOD, "stringField");
            STRING_FIELD_SETTER_OBJECT_PROPERTY_WRITERS = STRING_FIELD_SETTER_OBJECT_SET_METHODS.stream().map(method -> PropertyWriter.<StringFieldSetterObject, String>from(StringFieldSetterObject.class, method, "stringField")).collect(ImmutableSet.toImmutableSet());
            BOOLEAN_FIELD_GET_METHOD_OBJECT_BOOLEAN_PROPERTY = ReadableProperty.create(ImmutableSet.of(BOOLEAN_FIELD_GET_METHOD_OBJECT_BOOLEAN_FIELD_PROPERTY_READER));
            BOOLEAN_FIELD_IS_METHOD_OBJECT_BOOLEAN_PROPERTY = ReadableProperty.create(ImmutableSet.of(BOOLEAN_FIELD_IS_METHOD_OBJECT_BOOLEAN_FIELD_PROPERTY_READER));
            CHILDREN_LONG_FIELD_OBJECT_STRING_PROPERTY = AccessibleProperty.create(ImmutableSet.of(CHILDREN_LONG_FIELD_OBJECT_STRING_FIELD_PROPERTY_ACCESSOR));
            CHILDREN_LONG_FIELD_OBJECT_LONG_PROPERTY = AccessibleProperty.create(ImmutableSet.of(CHILDREN_LONG_FIELD_OBJECT_LONG_FIELD_PROPERTY_ACCESSOR));
            CHILDREN_LONG_FIELD_OBJECT_PROPERTIES = ImmutableSet.of(CHILDREN_LONG_FIELD_OBJECT_STRING_PROPERTY, CHILDREN_LONG_FIELD_OBJECT_LONG_PROPERTY);
            CHILDREN_SAME_NAME_FIELD_OBJECT_STRING_PROPERTY = AccessibleProperty.create(CHILDREN_SAME_NAME_FIELD_OBJECT_PROPERTY_ACCESSORS);
            COMPOSITE_FIELD_OBJECT_INTERNAL_PROPERTY = AccessibleProperty.create(ImmutableSet.of(COMPOSITE_FIELD_OBJECT_INTERNAL_FIELD_PROPERTY_ACCESSOR));
            COMPOSITE_FIELD_OBJECT_INTERNAL_INTEGER_PROPERTY = COMPOSITE_FIELD_OBJECT_INTERNAL_PROPERTY.compose(ReflectionUtil.accessiblePropertyExact(CompositeFieldObject.Internal.class, CompositeFieldObject.Internal.Fields.VALUE));
            COMPOSITE_GETTER_OBJECT_INTERNAL_PROPERTY = ReadableProperty.create(ImmutableSet.of(COMPOSITE_GETTER_OBJECT_INTERNAL_PROPERTY_READER));
            COMPOSITE_GETTER_OBJECT_INTERNAL_INTEGER_PROPERTY = COMPOSITE_GETTER_OBJECT_INTERNAL_PROPERTY.compose(ReflectionUtil.readablePropertyExact(CompositeGetterObject.Internal.class, "value"));
            COMPOSITE_SETTER_OBJECT_INTERNAL_PROPERTY = ReadableProperty.create(ImmutableSet.of(COMPOSITE_SETTER_OBJECT_INTERNAL_PROPERTY_READER));
            COMPOSITE_SETTER_OBJECT_INTERNAL_INTEGER_PROPERTY = COMPOSITE_SETTER_OBJECT_INTERNAL_PROPERTY.compose(ReflectionUtil.writablePropertyExact(CompositeSetterObject.Internal.class, "value"));
            DOUBLE_GENERIC_FIELD_OBJECT_GENERIC_PROPERTY = AccessibleProperty.create(ImmutableSet.of(DOUBLE_GENERIC_FIELD_OBJECT_GENERIC_FIELD_PROPERTY_ACCESSOR));
            DUPLICATE_NUMBER_FIELD_SET_METHOD_OBJECT_NUMBER_PROPERTY = WritableProperty.create(DUPLICATE_NUMBER_FIELD_SET_METHOD_OBJECT_PROPERTY_WRITERS);
            FINAL_FIELD_OBJECT_STRING_PROPERTY = AccessibleProperty.create(ImmutableSet.of(FINAL_FIELD_OBJECT_STRING_FIELD_PROPERTY_ACCESSOR));
            GENERIC_FIELD_GETTER_GENERIC_PROPERTY = ReadableProperty.create(ImmutableSet.of(GENERIC_FIELD_GETTER_GENERIC_FIELD_PROPERTY_READER));
            GENERIC_FIELD_OBJECT_GENERIC_PROPERTY = AccessibleProperty.create(ImmutableSet.of(GENERIC_FIELD_OBJECT_GENERIC_FIELD_PROPERTY_ACCESSOR));
            GENERIC_FIELD_SETTER_GENERIC_PROPERTY = WritableProperty.create(ImmutableSet.of(GENERIC_FIELD_SETTER_GENERIC_FIELD_PROPERTY_WRITER));
            INTEGER_GENERIC_FIELD_GETTER_GENERIC_PROPERTY = ReadableProperty.create(INTEGER_GENERIC_FIELD_GETTER_PROPERTY_READERS);
            LONG_GENERIC_FIELD_SETTER_GENERIC_PROPERTY = WritableProperty.create(LONG_GENERIC_FIELD_SETTER_PROPERTY_WRITERS);
            MULTIPLE_COMPOSITE_OBJECT_INTERNAL_PROPERTY = ReadableProperty.create(ImmutableSet.of(MULTIPLE_COMPOSITE_OBJECT_INTERNAL_PROPERTY_READER));
            MULTIPLE_COMPOSITE_OBJECT_INTERNAL_INTERNAL_PROPERTY = MULTIPLE_COMPOSITE_OBJECT_INTERNAL_PROPERTY.compose(ReflectionUtil.accessiblePropertyExact(MultipleCompositeObject.Internal.class, MultipleCompositeObject.Internal.Fields.INTERNAL));
            MULTIPLE_COMPOSITE_OBJECT_MULTIPLE_INTERNAL_PROPERTY = MULTIPLE_COMPOSITE_OBJECT_INTERNAL_INTERNAL_PROPERTY.compose(ReflectionUtil.accessiblePropertyExact(MultipleCompositeObject.Internal.class, MultipleCompositeObject.Internal.Fields.INTERNAL));
            MULTIPLE_FIELD_OBJECT_STRING_PROPERTY = AccessibleProperty.create(ImmutableSet.of(MULTIPLE_FIELD_OBJECT_STRING_FIELD_PROPERTY_ACCESSOR));
            MULTIPLE_FIELD_OBJECT_INTEGER_PROPERTY = AccessibleProperty.create(ImmutableSet.of(MULTIPLE_FIELD_OBJECT_INTEGER_FIELD_PROPERTY_ACCESSOR));
            MULTIPLE_FIELD_OBJECT_INT_PROPERTY = AccessibleProperty.create(ImmutableSet.of(MULTIPLE_FIELD_OBJECT_INT_FIELD_PROPERTY_ACCESSOR));
            MULTIPLE_FIELD_OBJECT_BOOLEAN_PROPERTY = AccessibleProperty.create(ImmutableSet.of(MULTIPLE_FIELD_OBJECT_BOOLEAN_FIELD_PROPERTY_ACCESSOR));
            MULTIPLE_FIELD_OBJECT_PROPERTIES = ImmutableSet.of(MULTIPLE_FIELD_OBJECT_STRING_PROPERTY, MULTIPLE_FIELD_OBJECT_INTEGER_PROPERTY, MULTIPLE_FIELD_OBJECT_INT_PROPERTY, MULTIPLE_FIELD_OBJECT_BOOLEAN_PROPERTY);
            STRING_FIELD_AND_STRING_FIELD_GET_METHOD_OBJECT_STRING_PROPERTY = AccessibleProperty.create(STRING_FIELD_AND_STRING_FIELD_GET_METHOD_OBJECT_PROPERTY_READERS, ImmutableSet.of(STRING_FIELD_AND_STRING_FIELD_GET_METHOD_OBJECT_STRING_FIELD_PROPERTY_ACCESSOR));
            STRING_FIELD_AND_STRING_FIELD_SET_METHOD_OBJECT_STRING_PROPERTY = AccessibleProperty.create(ImmutableSet.of(STRING_FIELD_AND_STRING_FIELD_SET_METHOD_OBJECT_STRING_FIELD_PROPERTY_ACCESSOR), STRING_FIELD_AND_STRING_FIELD_SET_METHOD_OBJECT_PROPERTY_WRITERS);
            STRING_FIELD_CHAIN_SET_METHOD_OBJECT_STRING_PROPERTY = WritableProperty.create(ImmutableSet.of(STRING_FIELD_CHAIN_SET_METHOD_OBJECT_SET_STRING_FIELD_METHOD_PROPERTY_WRITER));
            STRING_FIELD_FLUENT_GET_METHOD_OBJECT_STRING_PROPERTY = ReadableProperty.create(ImmutableSet.of(STRING_FIELD_FLUENT_GET_METHOD_OBJECT_STRING_FIELD_PROPERTY_READER));
            STRING_FIELD_FLUENT_SET_METHOD_OBJECT_STRING_PROPERTY = WritableProperty.create(ImmutableSet.of(STRING_FIELD_FLUENT_SET_METHOD_OBJECT_STRING_FIELD_METHOD_PROPERTY_WRITER));
            STRING_FIELD_GET_METHOD_OBJECT_STRING_PROPERTY = ReadableProperty.create(ImmutableSet.of(STRING_FIELD_GET_METHOD_OBJECT_STRING_FIELD_PROPERTY_READER));
            STRING_FIELD_GETTER_STRING_PROPERTY = ReadableProperty.create(ImmutableSet.of(STRING_FIELD_GETTER_STRING_FIELD_PROPERTY_READER));
            STRING_FIELD_GETTER_OBJECT_STRING_PROPERTY = ReadableProperty.create(STRING_FIELD_GETTER_OBJECT_PROPERTY_READERS);
            STRING_FIELD_OBJECT_STRING_PROPERTY = AccessibleProperty.create(ImmutableSet.of(STRING_FIELD_OBJECT_STRING_FIELD_PROPERTY_ACCESSOR));
            STRING_FIELD_SET_METHOD_OBJECT_STRING_PROPERTY = WritableProperty.create(ImmutableSet.of(STRING_FIELD_SET_METHOD_OBJECT_SET_STRING_FIELD_METHOD_PROPERTY_WRITER));
            STRING_FIELD_SETTER_STRING_PROPERTY = WritableProperty.create(ImmutableSet.of(STRING_FIELD_SETTER_SET_STRING_FIELD_METHOD_PROPERTY_WRITER));
            STRING_FIELD_SETTER_OBJECT_STRING_PROPERTY = WritableProperty.create(STRING_FIELD_SETTER_OBJECT_PROPERTY_WRITERS);
        } catch (NoSuchFieldException | NoSuchMethodException e) {
            throw new RuntimeException(e);
        }
    }
}
